sonar.projectKey=closeurcase-ai-be
sonar.projectName=closeurcase-AI-be
sonar.sources=src,main.py
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.ruff.reportPaths=ruff-report.json
sonar.exclusions=.venv/**,**/__pycache__/**
